### ISSUE TITLE
Error within discord.py stops the bot from launching

### ISSUE THREAD

**Issue by HASJ** [itsmrpeck/sglobbylink-discord.py#1]
```Traceback (most recent call last):
  File "D:\SGBRbot\SGBRbot.py", line 7, in <module>
    import discord
  File "C:\Python37\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Python37\lib\site-packages\discord\client.py", line 38, in <module>
    from .state import ConnectionState
  File "C:\Python37\lib\site-packages\discord\state.py", line 36, in <module>
    from . import utils, compat
  File "C:\Python37\lib\site-packages\discord\compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax```

I don't understand what is going on. Could you help me?

**Comment by HASJ** [comment]
Thanks, man.
